# Generated by Django 4.2 on 2023-05-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loeffa", "0002_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="name_user",
            field=models.CharField(default="Gustavo Reis", max_length=50),
        ),
    ]
